//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ImageInfors = new HashSet<ImageInfor>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<int> ProductSold { get; set; }
        public string ProductDescription { get; set; }
        public string ProductSupplier { get; set; }
        public Nullable<int> ProductStateId { get; set; }
        public Nullable<double> ProductSale { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ImageInfor> ImageInfors { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ProductState ProductState { get; set; }
    }
}
